# -*- coding: utf-8 -*-
"""
alliance_missions.py — Alliance Mission System
===============================================
Two mission tiers running in parallel:

DAILY ALLIANCE MISSIONS:
  - 10 missions generated fresh every 24h (D through S rank)
  - Alliance leader sees all 10, selects exactly 3 for members
  - Members see only the 3 chosen missions
  - Completing a mission earns AP for every contributor
  - Missions reset at midnight UTC regardless of completion

COMMANDER PRIORITY MISSIONS:
  - Issued by the Gamemaster persona (the bot)
  - Time-limited (2–8 hours), story-flavoured, high reward
  - All alliances see the same priority missions simultaneously
  - Leader must accept before members can work on it
  - Server-wide announcement when a priority mission is issued

MISSION RANKS:
  D — Simple solo tasks. Low AP. Any member can solo.
  C — Light coordination. 2 members needed.
  B — Group effort. Requires alliance presence in a sector.
  A — Strategic operations. Multiple sectors, time pressure.
  S — Alliance-wide mobilisation. Maximum reward. Rare.
"""

import random
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

# ═══════════════════════════════════════════════════════════════════════════
#  MISSION TEMPLATES
#  These are the building blocks. Missions are generated by selecting
#  a template, filling in variables, and assigning a rank.
# ═══════════════════════════════════════════════════════════════════════════

MISSION_TEMPLATES: List[dict] = [

    # ── D RANK — Solo tasks ───────────────────────────────────────────────
    {
        "rank": "D",
        "id":   "collect_wood",
        "name": "Timber Run",
        "desc": "Collect {amount} wood from any sector node.",
        "vars": {"amount": [200, 300, 400]},
        "objective_type": "collect_resource",
        "objective_resource": "wood",
        "ap_reward": 25,
        "gold_reward": 10,
        "time_hours": 24,
        "flavor": "The base needs timber. Don't overthink it.",
        "contributors_needed": 1,
    },
    {
        "rank": "D",
        "id":   "collect_iron",
        "name": "Iron Harvest",
        "desc": "Collect {amount} iron from sector nodes.",
        "vars": {"amount": [150, 200, 250]},
        "objective_type": "collect_resource",
        "objective_resource": "iron",
        "ap_reward": 30,
        "gold_reward": 15,
        "time_hours": 24,
        "flavor": "Iron is the spine of every empire.",
        "contributors_needed": 1,
    },
    {
        "rank": "D",
        "id":   "train_troops_d",
        "name": "Basic Drill",
        "desc": "Train {amount} troops of any type.",
        "vars": {"amount": [10, 20, 30]},
        "objective_type": "train_troops",
        "ap_reward": 25,
        "gold_reward": 10,
        "time_hours": 24,
        "flavor": "Every soldier starts as a recruit.",
        "contributors_needed": 1,
    },
    {
        "rank": "D",
        "id":   "upgrade_building_d",
        "name": "Construction Push",
        "desc": "Complete {amount} building upgrade(s).",
        "vars": {"amount": [1, 2]},
        "objective_type": "upgrade_buildings",
        "ap_reward": 30,
        "gold_reward": 15,
        "time_hours": 24,
        "flavor": "A base that isn't growing is dying.",
        "contributors_needed": 1,
    },
    {
        "rank": "D",
        "id":   "scout_player",
        "name": "Eyes Open",
        "desc": "Successfully scout {amount} player(s).",
        "vars": {"amount": [1, 2]},
        "objective_type": "scout_players",
        "ap_reward": 20,
        "gold_reward": 10,
        "time_hours": 24,
        "flavor": "Know your enemies before you move.",
        "contributors_needed": 1,
    },

    # ── C RANK — Light coordination ────────────────────────────────────────
    {
        "rank": "C",
        "id":   "sector_presence",
        "name": "Show of Force",
        "desc": "Have {amount} alliance members occupy nodes in the same sector simultaneously.",
        "vars": {"amount": [2, 3]},
        "objective_type": "simultaneous_sector_presence",
        "ap_reward": 75,
        "gold_reward": 30,
        "time_hours": 24,
        "flavor": "Presence is power. Numbers matter.",
        "contributors_needed": 2,
    },
    {
        "rank": "C",
        "id":   "collect_relics_c",
        "name": "Relic Extraction",
        "desc": "Collect {amount} relics combined across all alliance members.",
        "vars": {"amount": [30, 50, 75]},
        "objective_type": "collect_resource_combined",
        "objective_resource": "relics",
        "ap_reward": 80,
        "gold_reward": 35,
        "time_hours": 24,
        "flavor": "The ancient artifacts don't collect themselves.",
        "contributors_needed": 2,
    },
    {
        "rank": "C",
        "id":   "win_battles_c",
        "name": "Combat Operations",
        "desc": "Win {amount} node battles combined across the alliance.",
        "vars": {"amount": [3, 5]},
        "objective_type": "win_battles",
        "ap_reward": 100,
        "gold_reward": 40,
        "time_hours": 24,
        "flavor": "Winning isn't enough. Win decisively.",
        "contributors_needed": 2,
    },
    {
        "rank": "C",
        "id":   "research_complete_c",
        "name": "Knowledge Drive",
        "desc": "Complete {amount} research project(s) across the alliance.",
        "vars": {"amount": [2, 3]},
        "objective_type": "complete_research",
        "ap_reward": 75,
        "gold_reward": 30,
        "time_hours": 24,
        "flavor": "An alliance that doesn't learn, stagnates.",
        "contributors_needed": 2,
    },

    # ── B RANK — Group effort ─────────────────────────────────────────────
    {
        "rank": "B",
        "id":   "hold_pvp_node",
        "name": "Outpost Control",
        "desc": "Hold a PvP outpost node in any sector for {minutes} combined minutes.",
        "vars": {"minutes": [30, 45, 60]},
        "objective_type": "hold_pvp_node_minutes",
        "ap_reward": 150,
        "gold_reward": 75,
        "time_hours": 24,
        "flavor": "He who controls the high ground, controls the sector.",
        "contributors_needed": 2,
    },
    {
        "rank": "B",
        "id":   "eject_players_b",
        "name": "Territorial Sweep",
        "desc": "Eject {amount} enemy players from your alliance's primary sector.",
        "vars": {"amount": [3, 5]},
        "objective_type": "eject_players",
        "ap_reward": 175,
        "gold_reward": 80,
        "time_hours": 24,
        "flavor": "Make them understand this is your territory.",
        "contributors_needed": 3,
    },
    {
        "rank": "B",
        "id":   "contribute_treasury",
        "name": "Alliance Treasury Drive",
        "desc": "Contribute {amount} total resources to the alliance treasury.",
        "vars": {"amount": [500, 750, 1000]},
        "objective_type": "contribute_treasury",
        "ap_reward": 150,
        "gold_reward": 60,
        "time_hours": 24,
        "flavor": "An alliance is only as strong as its shared wealth.",
        "contributors_needed": 3,
    },
    {
        "rank": "B",
        "id":   "kill_predator_b",
        "name": "Monster Hunt",
        "desc": "Defeat {amount} sector predator(s) with multiple alliance members contributing.",
        "vars": {"amount": [2, 3]},
        "objective_type": "kill_predators",
        "ap_reward": 160,
        "gold_reward": 70,
        "time_hours": 24,
        "flavor": "Hunt together. Share the kill.",
        "contributors_needed": 2,
    },

    # ── A RANK — Strategic operations ─────────────────────────────────────
    {
        "rank": "A",
        "id":   "multi_sector_dominance",
        "name": "Sector Expansion",
        "desc": "Have alliance members holding nodes in {amount} different sectors simultaneously.",
        "vars": {"amount": [3, 4]},
        "objective_type": "multi_sector_presence",
        "ap_reward": 300,
        "gold_reward": 150,
        "time_hours": 24,
        "flavor": "Empires are built across borders, not within them.",
        "contributors_needed": 3,
    },
    {
        "rank": "A",
        "id":   "win_sector_cycle",
        "name": "Cycle Domination",
        "desc": "End the current dominance cycle as the top-scoring alliance in any sector.",
        "vars": {},
        "objective_type": "win_dominance_cycle",
        "ap_reward": 400,
        "gold_reward": 200,
        "time_hours": 24,
        "flavor": "Rule the cycle. Rule the sector.",
        "contributors_needed": 3,
    },
    {
        "rank": "A",
        "id":   "collective_bitcoin",
        "name": "Crypto Raid",
        "desc": "Collect {amount} Satoshi combined from the Crypto Wastes.",
        "vars": {"amount": [5000, 7500, 10000]},
        "objective_type": "collect_resource_combined",
        "objective_resource": "satoshi",
        "ap_reward": 350,
        "gold_reward": 175,
        "time_hours": 24,
        "flavor": "The Crypto Wastes are dangerous. That's why the rewards are high.",
        "contributors_needed": 3,
    },

    # ── S RANK — Full mobilisation ─────────────────────────────────────────
    {
        "rank": "S",
        "id":   "alliance_war_win",
        "name": "Total War Victory",
        "desc": "Win an active alliance war by outscoring the enemy alliance.",
        "vars": {},
        "objective_type": "win_alliance_war",
        "ap_reward": 1000,
        "gold_reward": 500,
        "time_hours": 24,
        "flavor": "War is the final argument. Win it.",
        "contributors_needed": 5,
    },
    {
        "rank": "S",
        "id":   "capture_vault_sector",
        "name": "Vault Seizure",
        "desc": "Have an alliance member become Sector Ruler of a Vault Sector (60-64).",
        "vars": {},
        "objective_type": "become_vault_ruler",
        "ap_reward": 800,
        "gold_reward": 400,
        "time_hours": 24,
        "flavor": "The vaults hold the greatest treasures. Take them.",
        "contributors_needed": 4,
    },
    {
        "rank": "S",
        "id":   "void_survival",
        "name": "Void Runners",
        "desc": "Have {amount} alliance members survive a full Void Canyon cycle without ejection.",
        "vars": {"amount": [3, 4]},
        "objective_type": "survive_void_cycle",
        "ap_reward": 900,
        "gold_reward": 450,
        "time_hours": 24,
        "flavor": "The void kills the unprepared. Prove you're not unprepared.",
        "contributors_needed": 3,
    },
]

# Commander Priority Mission templates (rarer, story-flavoured)
PRIORITY_MISSION_TEMPLATES: List[dict] = [
    {
        "id":           "priority_void_incursion",
        "name":         "PRIORITY: Void Incursion",
        "desc":         "Intelligence reports unusual void energy concentration in Sector 9. "
                        "Deploy {amount} commanders to Void Canyon within {hours} hours.",
        "vars":         {"amount": [2, 3], "hours": [3, 4]},
        "objective_type": "commanders_in_sector",
        "objective_sector": 9,
        "ap_reward":    500,
        "gold_reward":  250,
        "item_reward":  "void_suit",
        "time_hours":   4,
        "flavor":       "The void doesn't wait. Neither should you.",
        "rank":         "A",
        "server_wide":  True,
    },
    {
        "id":           "priority_crypto_crash",
        "name":         "PRIORITY: Market Crash Response",
        "desc":         "A market crash is imminent in the Crypto Wastes. "
                        "Extract {amount} Satoshi before the collapse.",
        "vars":         {"amount": [3000, 5000]},
        "objective_type": "collect_resource_combined",
        "objective_resource": "satoshi",
        "ap_reward":    400,
        "gold_reward":  200,
        "item_reward":  "bitcoin_format",
        "time_hours":   2,
        "flavor":       "The window is closing. Move now or miss the extraction entirely.",
        "rank":         "B",
        "server_wide":  True,
    },
    {
        "id":           "priority_sector_siege",
        "name":         "PRIORITY: Sector Siege",
        "desc":         "A rival alliance has taken control of Sector {sector}. "
                        "Dislodge their forces within {hours} hours.",
        "vars":         {"sector": [3, 6, 8], "hours": [4, 6]},
        "objective_type": "eject_players",
        "ap_reward":    600,
        "gold_reward":  300,
        "item_reward":  "speedup_30m",
        "time_hours":   6,
        "flavor":       "This is not a request. This is an order.",
        "rank":         "S",
        "server_wide":  True,
    },
    {
        "id":           "priority_predator_wave",
        "name":         "PRIORITY: Predator Surge",
        "desc":         "Multiple predators have spawned across sectors. "
                        "Defeat {amount} predators within {hours} hours.",
        "vars":         {"amount": [5, 8], "hours": [3, 4]},
        "objective_type": "kill_predators",
        "ap_reward":    450,
        "gold_reward":  225,
        "item_reward":  "hazmat_suit",
        "time_hours":   4,
        "flavor":       "They breed fast. Kill faster.",
        "rank":         "B",
        "server_wide":  True,
    },
]

RANK_COLORS = {"D": "⬜", "C": "🟩", "B": "🟦", "A": "🟪", "S": "🟥"}
RANK_ORDER  = {"D": 0, "C": 1, "B": 2, "A": 3, "S": 4}


# ═══════════════════════════════════════════════════════════════════════════
#  MISSION GENERATION
# ═══════════════════════════════════════════════════════════════════════════

def generate_daily_missions(seed_date: str = None) -> List[dict]:
    """
    Generate 10 daily missions with varied ranks.
    Seed by date so all alliances see the same pool (just different selections).
    Rank distribution: 3×D, 3×C, 2×B, 1×A, 1×S
    """
    if seed_date is None:
        seed_date = datetime.utcnow().strftime("%Y-%m-%d")

    rng = random.Random(seed_date)   # Deterministic for the day

    rank_targets = {"D": 3, "C": 3, "B": 2, "A": 1, "S": 1}
    selected     = []

    for rank, count in rank_targets.items():
        pool = [t for t in MISSION_TEMPLATES if t["rank"] == rank]
        chosen = rng.sample(pool, min(count, len(pool)))

        for template in chosen:
            mission = _instantiate_mission(template, seed_date, rng)
            selected.append(mission)

    # Shuffle so rank order isn't always the same visual layout
    rng.shuffle(selected)
    return selected


def generate_priority_mission() -> dict:
    """Generate a single priority mission (server-wide, time-limited)."""
    template = random.choice(PRIORITY_MISSION_TEMPLATES)
    mission  = _instantiate_mission(template, datetime.utcnow().isoformat(), random)
    mission["is_priority"]  = True
    mission["expires_at"]   = (
        datetime.utcnow() + timedelta(hours=mission["time_hours"])
    ).isoformat()
    mission["issued_at"]    = datetime.utcnow().isoformat()
    return mission


def _instantiate_mission(template: dict, seed: str, rng) -> dict:
    """Fill in a mission template with concrete variable values."""
    mission = dict(template)
    var_choices = {}

    for var_name, options in template.get("vars", {}).items():
        if isinstance(options, list) and options:
            var_choices[var_name] = rng.choice(options)
        else:
            var_choices[var_name] = options

    mission["desc"]     = template["desc"].format(**var_choices)
    mission["name"]     = template["name"]
    mission["vars"]     = var_choices
    mission["mission_id"] = f"{template['id']}_{seed[:10]}"
    mission["progress"] = {}   # {player_id: contribution_amount}
    mission["completed"] = False
    mission["completed_at"] = None
    mission["completions"] = []  # List of player_ids who completed

    return mission


# ═══════════════════════════════════════════════════════════════════════════
#  ALLIANCE MISSION MANAGEMENT
# ═══════════════════════════════════════════════════════════════════════════

def get_or_generate_today_missions(alliance: dict) -> List[dict]:
    """
    Get today's mission pool for an alliance.
    Generates new ones if it's a new day.
    """
    today      = datetime.utcnow().strftime("%Y-%m-%d")
    pool       = alliance.get("mission_pool", {})

    if not isinstance(pool, dict):
        pool = {}

    if pool.get("date") == today and pool.get("missions"):
        return pool["missions"]

    # Generate fresh missions for today
    missions               = generate_daily_missions(today)
    alliance["mission_pool"] = {
        "date":         today,
        "missions":     missions,
        "selected_ids": [],   # Leader hasn't selected yet
    }
    return missions


def leader_select_missions(
    alliance: dict,
    leader_user: dict,
    mission_ids: List[str],
) -> Tuple[bool, str, dict]:
    """
    Alliance leader selects exactly 3 missions from the pool.
    Returns (success, message, updated_alliance)
    """
    role = leader_user.get("alliance_role", "MEMBER")
    if role != "LEADER":
        return False, "❌ Only the alliance leader can select missions.", alliance

    if len(mission_ids) != 3:
        return False, f"❌ Select exactly 3 missions. You selected {len(mission_ids)}.", alliance

    pool = alliance.get("mission_pool", {})
    if not pool.get("missions"):
        alliance = _init_pool(alliance)
        pool     = alliance["mission_pool"]

    available_ids = [m["mission_id"] for m in pool.get("missions", [])]

    for mid in mission_ids:
        if mid not in available_ids:
            return False, f"❌ Mission {mid} not in today's pool.", alliance

    pool["selected_ids"] = mission_ids
    alliance["mission_pool"] = pool

    selected_names = [
        m["name"] for m in pool["missions"]
        if m["mission_id"] in mission_ids
    ]
    return True, (
        f"✅ *3 missions assigned to your alliance:*\n"
        + "\n".join(f"  • {n}" for n in selected_names)
        + "\n\nMembers can now complete these to earn Alliance Points."
    ), alliance


def get_active_missions(alliance: dict) -> List[dict]:
    """Get the 3 missions currently active for members."""
    pool = alliance.get("mission_pool", {})
    if not isinstance(pool, dict):
        return []

    selected_ids = pool.get("selected_ids", [])
    all_missions = pool.get("missions", [])

    if not selected_ids:
        return []

    return [m for m in all_missions if m["mission_id"] in selected_ids]


def record_mission_progress(
    alliance: dict,
    player_id: str,
    objective_type: str,
    amount: int = 1,
    resource: str = None,
    sector_id: int = None,
) -> Tuple[dict, List[str]]:
    """
    Record player progress toward active missions.
    Called by other systems when relevant actions happen
    (resource collected, battle won, etc.)

    Returns (updated_alliance, list_of_completed_mission_names)
    """
    active       = get_active_missions(alliance)
    pool         = alliance.get("mission_pool", {})
    completed    = []

    for mission in pool.get("missions", []):
        if mission["mission_id"] not in pool.get("selected_ids", []):
            continue
        if mission.get("completed"):
            continue

        m_type     = mission.get("objective_type", "")
        m_resource = mission.get("objective_resource")

        # Check if this action matches the mission
        matches = False
        if m_type == objective_type:
            if m_resource and resource and m_resource != resource:
                matches = False
            else:
                matches = True

        if not matches:
            continue

        # Record progress
        if "progress" not in mission or not isinstance(mission.get("progress"), dict):
            mission["progress"] = {}

        mission["progress"][player_id] = mission["progress"].get(player_id, 0) + amount

        # Check completion
        target   = mission.get("vars", {}).get("amount", mission.get("vars", {}).get("minutes", 1))
        if isinstance(target, list):
            target = target[-1]  # Use the value that was chosen
        target   = mission["vars"].get("amount", target) if mission.get("vars") else target

        total_progress = sum(mission["progress"].values())

        if total_progress >= target and not mission.get("completed"):
            mission["completed"]    = True
            mission["completed_at"] = datetime.utcnow().isoformat()
            mission["completions"].append(player_id)
            completed.append(mission["name"])

            # Award AP to all contributors
            ap_reward = mission.get("ap_reward", 50)
            alliance  = _distribute_ap(alliance, mission["progress"], ap_reward)

    return alliance, completed


def _distribute_ap(alliance: dict, contributors: dict, total_ap: int) -> dict:
    """
    Distribute AP reward proportionally among contributors.
    Stored per-member for them to claim, or added to alliance pool.
    """
    if not contributors:
        return alliance

    # Equal split among all contributors
    share = max(1, total_ap // len(contributors))

    if "pending_ap_rewards" not in alliance:
        alliance["pending_ap_rewards"] = {}
    if not isinstance(alliance.get("pending_ap_rewards"), dict):
        alliance["pending_ap_rewards"] = {}

    for pid in contributors:
        alliance["pending_ap_rewards"][pid] = (
            alliance["pending_ap_rewards"].get(pid, 0) + share
        )

    return alliance


def claim_ap_rewards(alliance: dict, player_id: str, user: dict) -> Tuple[int, dict, dict]:
    """
    Player claims their pending AP rewards from completed missions.
    Returns (ap_claimed, updated_user, updated_alliance)
    """
    pending = alliance.get("pending_ap_rewards", {})
    if not isinstance(pending, dict):
        pending = {}

    amount = pending.pop(player_id, 0)
    if amount > 0:
        user["alliance_points"] = user.get("alliance_points", 0) + amount
        alliance["alliance_points"] = alliance.get("alliance_points", 0) + amount
        alliance["pending_ap_rewards"] = pending

    return amount, user, alliance


def accept_priority_mission(
    alliance: dict,
    leader_user: dict,
    priority_mission: dict,
) -> Tuple[bool, str, dict]:
    """Leader accepts a priority mission for the alliance."""
    role = leader_user.get("alliance_role", "MEMBER")
    if role != "LEADER":
        return False, "❌ Only the alliance leader can accept priority missions.", alliance

    if alliance.get("active_priority_mission"):
        existing = alliance["active_priority_mission"].get("name", "?")
        return False, f"❌ Already have an active priority mission: {existing}", alliance

    alliance["active_priority_mission"] = {
        **priority_mission,
        "accepted_at": datetime.utcnow().isoformat(),
        "progress":    {},
    }
    return True, (
        f"🚨 *Priority Mission Accepted!*\n"
        f"*{priority_mission['name']}*\n"
        f"{priority_mission['desc']}\n\n"
        f"Reward: {priority_mission['ap_reward']} AP + {priority_mission['gold_reward']} Gold"
        + (f" + {priority_mission.get('item_reward','').replace('_',' ').title()}" if priority_mission.get('item_reward') else "")
        + f"\n\nTime limit: {priority_mission['time_hours']}h"
    ), alliance


def _init_pool(alliance: dict) -> dict:
    """Initialise mission pool if missing."""
    today = datetime.utcnow().strftime("%Y-%m-%d")
    alliance["mission_pool"] = {
        "date":         today,
        "missions":     generate_daily_missions(today),
        "selected_ids": [],
    }
    return alliance


# ═══════════════════════════════════════════════════════════════════════════
#  DISPLAY FORMATTERS
# ═══════════════════════════════════════════════════════════════════════════

def format_mission_pool(alliance: dict, is_leader: bool = False) -> str:
    """Format the full mission pool for leader view (all 10)."""
    pool     = alliance.get("mission_pool", {})
    missions = get_or_generate_today_missions(alliance)
    selected = pool.get("selected_ids", [])
    today    = datetime.utcnow().strftime("%Y-%m-%d")

    lines = [
        "📋 *DAILY MISSION POOL*",
        f"Date: {today}  |  Reset: midnight UTC",
        f"━━━━━━━━━━━━━━━━━━━━━━━━",
    ]

    if is_leader:
        if len(selected) < 3:
            lines.append(f"⚠️ *Select 3 missions for your members.*\n")
        else:
            lines.append(f"✅ *{len(selected)} missions assigned to members.*\n")

    for m in missions:
        rank      = m.get("rank", "D")
        color     = RANK_COLORS.get(rank, "⬜")
        name      = m.get("name", "?")
        desc      = m.get("desc", "")
        ap        = m.get("ap_reward", 0)
        gold      = m.get("gold_reward", 0)
        mid       = m.get("mission_id", "")
        completed = m.get("completed", False)
        is_sel    = mid in selected

        status = "✅" if completed else ("🎯" if is_sel else ("" if is_leader else ""))
        lines.append(
            f"\n{color} *[{rank}] {name}* {status}\n"
            f"  {desc}\n"
            f"  Reward: +{ap} AP  +{gold} 🪙"
        )

    lines.append(f"\n━━━━━━━━━━━━━━━━━━━━━━━━")
    if is_leader:
        lines.append("Tap missions below to select/deselect 3 for your members.")

    return "\n".join(lines)


def format_member_missions(alliance: dict) -> str:
    """Format active missions for member view (only the 3 selected)."""
    active = get_active_missions(alliance)

    if not active:
        return (
            "📋 *ALLIANCE MISSIONS*\n"
            "━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
            "_Your alliance leader hasn't assigned today's missions yet._\n"
            "Check back soon."
        )

    lines = [
        "📋 *YOUR ALLIANCE MISSIONS*",
        "━━━━━━━━━━━━━━━━━━━━━━━━",
    ]

    for m in active:
        rank      = m.get("rank", "D")
        color     = RANK_COLORS.get(rank, "⬜")
        name      = m.get("name", "?")
        desc      = m.get("desc", "")
        ap        = m.get("ap_reward", 0)
        gold      = m.get("gold_reward", 0)
        completed = m.get("completed", False)
        progress  = m.get("progress", {})
        flavor    = m.get("flavor", "")

        total_prog = sum(progress.values())
        target_val = m.get("vars", {}).get("amount", m.get("vars", {}).get("minutes", 1))
        if isinstance(target_val, list):
            target_val = target_val[-1]

        if completed:
            status = "✅ COMPLETE"
            bar    = "████████████████████ 100%"
        else:
            pct    = min(100, int((total_prog / max(target_val, 1)) * 100))
            filled = pct // 5
            bar    = "█" * filled + "░" * (20 - filled) + f" {pct}%"
            status = f"[{bar}]  {total_prog}/{target_val}"

        lines.append(
            f"\n{color} *[{rank}] {name}*\n"
            f"  _{flavor}_\n"
            f"  {desc}\n"
            f"  {status}\n"
            f"  Reward: +{ap} AP  +{gold} 🪙"
        )

    lines.append(f"\n━━━━━━━━━━━━━━━━━━━━━━━━")

    # Pending AP
    pending = alliance.get("pending_ap_rewards", {})
    if isinstance(pending, dict) and pending:
        total_pending = sum(pending.values())
        if total_pending > 0:
            lines.append(f"💰 *{total_pending} AP ready to claim* — tap Claim below")

    return "\n".join(lines)


def format_priority_mission(mission: dict) -> str:
    """Format a priority mission display."""
    if not mission:
        return "_No priority mission active._"

    rank      = mission.get("rank", "A")
    color     = RANK_COLORS.get(rank, "🟪")
    name      = mission.get("name", "?")
    desc      = mission.get("desc", "")
    ap        = mission.get("ap_reward", 0)
    gold      = mission.get("gold_reward", 0)
    item      = mission.get("item_reward", "")
    flavor    = mission.get("flavor", "")
    hours     = mission.get("time_hours", 4)
    expires   = mission.get("expires_at", "")
    completed = mission.get("completed", False)

    time_str = "?"
    if expires:
        try:
            exp     = datetime.fromisoformat(expires)
            rem     = exp - datetime.utcnow()
            h       = max(0, int(rem.total_seconds() // 3600))
            m       = max(0, int((rem.total_seconds() % 3600) // 60))
            time_str = f"{h}h {m}m remaining"
        except Exception:
            time_str = "?"

    item_str = f" + {item.replace('_',' ').title()}" if item else ""

    lines = [
        f"🚨 *PRIORITY ORDER*",
        f"━━━━━━━━━━━━━━━━━━━━━━━━",
        f"{color} *[{rank}] {name}*",
        f"",
        f"_{flavor}_",
        f"",
        f"{desc}",
        f"",
        f"⏱️ Time: *{time_str}*",
        f"🏆 Reward: +{ap} AP  +{gold} 🪙{item_str}",
        f"{'✅ COMPLETED' if completed else ''}",
        f"━━━━━━━━━━━━━━━━━━━━━━━━",
    ]
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
#  INLINE KEYBOARDS
# ═══════════════════════════════════════════════════════════════════════════

def kb_mission_hub(user: dict, alliance: dict) -> InlineKeyboardMarkup:
    """Main mission hub keyboard."""
    is_leader = user.get("alliance_role") == "LEADER"
    pending   = alliance.get("pending_ap_rewards", {})
    my_ap     = pending.get(user.get("user_id"), 0) if isinstance(pending, dict) else 0

    buttons = []

    if is_leader:
        buttons.append([
            InlineKeyboardButton(text="📋 Assign Missions", callback_data="mission:leader_pool"),
            InlineKeyboardButton(text="🚨 Priority Missions", callback_data="mission:priority"),
        ])

    buttons.append([
        InlineKeyboardButton(text="🎯 My Missions", callback_data="mission:member_view"),
    ])

    if my_ap > 0:
        buttons.append([
            InlineKeyboardButton(text=f"💰 Claim {my_ap} AP", callback_data="mission:claim_ap"),
        ])

    buttons.append([
        InlineKeyboardButton(text="⬅️ Alliance", callback_data="menu_guild"),
    ])

    return InlineKeyboardMarkup(inline_keyboard=buttons)


def kb_leader_mission_select(alliance: dict) -> InlineKeyboardMarkup:
    """Leader selection keyboard — tap to select/deselect missions."""
    pool     = alliance.get("mission_pool", {})
    missions = pool.get("missions", [])
    selected = pool.get("selected_ids", [])
    buttons  = []

    for m in missions:
        mid   = m.get("mission_id", "")
        rank  = m.get("rank", "D")
        name  = m.get("name", "?")
        color = RANK_COLORS.get(rank, "⬜")
        is_sel = mid in selected
        label = f"{'✅' if is_sel else '☐'} {color}[{rank}] {name}"
        buttons.append([InlineKeyboardButton(
            text=label,
            callback_data=f"mission:toggle:{mid}"
        )])

    if len(selected) == 3:
        buttons.append([InlineKeyboardButton(
            text="✅ Confirm Selection",
            callback_data="mission:confirm_selection"
        )])

    buttons.append([InlineKeyboardButton(text="⬅️ Back", callback_data="mission:hub")])
    return InlineKeyboardMarkup(inline_keyboard=buttons)


def kb_priority_mission(alliance: dict, user: dict) -> InlineKeyboardMarkup:
    """Priority mission keyboard."""
    is_leader = user.get("alliance_role") == "LEADER"
    active    = alliance.get("active_priority_mission")
    buttons   = []

    if is_leader and not active:
        buttons.append([InlineKeyboardButton(
            text="🚨 Accept Priority Mission",
            callback_data="mission:accept_priority"
        )])

    buttons.append([InlineKeyboardButton(text="⬅️ Back", callback_data="mission:hub")])
    return InlineKeyboardMarkup(inline_keyboard=buttons)