# inventory/registry.py

ITEM_REGISTRY = {
    # ── Protection & Suits ───────────────────────────────────────────────
    "basic_suit": {
        "name": "🧪 Basic Radiation Suit",
        "desc": "Protects from radiation hazards. 10 minutes.",
        "price": 80,
        "currency": "credits",
        "category": "protection",
        "effect_key": "basic_suit",
        "duration_m": 10,
        "qty": 1,
    },
    "hazmat_suit": {
        "name": "☢️ Hazmat Suit",
        "desc": "Full hazmat protection. 20 minutes.",
        "price": 180,
        "currency": "credits",
        "category": "protection",
        "effect_key": "hazmat_suit",
        "duration_m": 20,
        "qty": 1,
    },
    "void_suit": {
        "name": "🌑 Void Suit",
        "desc": "Void Canyon protection. 15 minutes.",
        "price": 350,
        "currency": "credits",
        "category": "protection",
        "effect_key": "void_suit",
        "duration_m": 15,
        "qty": 1,
    },
    "bitcoin_format": {
        "name": "💾 Bitcoin Format",
        "desc": "Crypto Wastes protection. 20 minutes.",
        "price": 300,
        "currency": "credits",
        "category": "protection",
        "effect_key": "bitcoin_format",
        "duration_m": 20,
        "qty": 1,
    },

    # ── Shields ──────────────────────────────────────────────────────────
    "shield_1h": {
        "name": "1-Hour Peace Shield",
        "desc": "Protect your base for 1 hour.",
        "price": 20,
        "currency": "credits",
        "category": "protection",
        "effect_key": "shield_item",
        "duration_h": 1,
        "qty": 1,
    },
    "shield_2h": {
        "name": "🛡️ 2-Hour Shield",
        "desc": "Protect your base for 2 hours.",
        "price": 40,
        "currency": "credits",
        "category": "protection",
        "effect_key": "shield_item",
        "duration_h": 2,
        "qty": 1,
    },
    "shield_8h": {
        "name": "🛡️ 8-Hour Base Shield",
        "desc": "Protects your base from raids for 8 hours.",
        "price": 152,
        "currency": "credits",
        "category": "protection",
        "effect_key": "shield_item",
        "duration_h": 8,
        "qty": 1,
    },
    "shield_24h": {
        "name": "🛡️ 1-Day Base Shield (24h)",
        "desc": "Full day of base protection.",
        "price": 408,
        "currency": "credits",
        "category": "protection",
        "effect_key": "shield_item",
        "duration_h": 24,
        "qty": 1,
    },
    "shield_72h": {
        "name": "🛡️ 3-Day Base Shield (72h)",
        "desc": "3-day base protection. Best value.",
        "price": 1008,
        "currency": "credits",
        "category": "protection",
        "effect_key": "shield_item",
        "duration_h": 72,
        "qty": 1,
    },

    # ── Speedups ─────────────────────────────────────────────────────────
    "speedup_building_15m": {
        "name": "15-Min Building Speedup",
        "desc": "Reduce building timer by 15 minutes.",
        "price": 8,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 15,
        "target": "building",
        "qty": 1,
    },
    "speedup_1m": {
        "name": "⏩ 1-Minute Speedup",
        "desc": "Reduce any timer by 1 minute.",
        "price": 1,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 1,
        "qty": 1,
    },
    "speedup_5m": {
        "name": "⏩ 5-Minute Speedup",
        "desc": "Reduce any timer by 5 minutes.",
        "price": 3,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 5,
        "qty": 1,
    },
    "speedup_15m": {
        "name": "⏩ 15-Minute Speedup",
        "desc": "Reduce any timer by 15 minutes.",
        "price": 8,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 15,
        "qty": 1,
    },
    "speedup_30m": {
        "name": "⏩ 30-Minute Speedup",
        "desc": "Reduce any timer by 30 minutes.",
        "price": 14,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 30,
        "qty": 1,
    },
    "speedup_1h": {
        "name": "⏩ 1-Hour Speedup",
        "desc": "Reduce any timer by 60 minutes.",
        "price": 27,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 60,
        "qty": 1,
    },
    "speedup_3h": {
        "name": "⏩ 3-Hour Speedup",
        "desc": "Reduce any timer by 3 hours.",
        "price": 77,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 180,
        "qty": 1,
    },
    "speedup_8h": {
        "name": "⏩ 8-Hour Speedup",
        "desc": "Reduce any timer by 8 hours.",
        "price": 180,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 480,
        "qty": 1,
    },
    "speedup_1day": {
        "name": "⏩ 1-Day Speedup",
        "desc": "Reduce any timer by 24 hours.",
        "price": 504,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 1440,
        "qty": 1,
    },
    "speedup_7day": {
        "name": "⏩ 7-Day Speedup",
        "desc": "Reduce any timer by 7 days.",
        "price": 4000,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 10080,
        "qty": 1,
    },
    "speedup_21day": {
        "name": "⏩ 21-Day Speedup",
        "desc": "Reduce any timer by 21 days.",
        "price": 6804,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 30240,
        "qty": 1,
    },
    "speedup_pack": {
        "name": "⏩ Speedup Pack (×5 30m)",
        "desc": "5× 30-minute speedups. Save 20%.",
        "price": 56,
        "currency": "credits",
        "category": "speedup",
        "effect_key": "speedup",
        "reduces_timer_minutes": 30,
        "qty": 5,
    },

    # ── Teleport Charges ──────────────────────────────────────────────────
    "teleport_1": {
        "name": "🌀 Quantum Teleport",
        "desc": "One additional teleport charge.",
        "price": 75,
        "currency": "credits",
        "category": "teleport",
        "effect_key": "teleport_charge",
        "qty": 1,
    },
    "teleport_5": {
        "name": "🌀 Teleport Core Pack",
        "desc": "5 charges. 15% off.",
        "price": 320,
        "currency": "credits",
        "category": "teleport",
        "effect_key": "teleport_charge",
        "qty": 5,
    },
    "teleport_10": {
        "name": "🌀 Sector Warp Matrix",
        "desc": "10 charges. Best value.",
        "price": 525,
        "currency": "credits",
        "category": "teleport",
        "effect_key": "teleport_charge",
        "qty": 10,
    },

    # ── Consumables & XP ──────────────────────────────────────────────────
    "energy_cell": {
        "name": "⚡ Energy Cell",
        "desc": "Restore 100 energy instantly.",
        "price": 25,
        "currency": "credits",
        "category": "consumable",
        "effect_key": "energy_restore",
        "energy": 100,
        "qty": 1,
    },
    "energy_pack": {
        "name": "⚡ Energy Pack",
        "desc": "5× energy cells. Save 20%.",
        "price": 100,
        "currency": "credits",
        "category": "consumable",
        "effect_key": "energy_restore",
        "energy": 100,
        "qty": 5,
    },
    "xp_chip_minor": {
        "name": "📁 Tactical Data Chip",
        "desc": "Add 250 XP to your commander. Useful for leveling up.",
        "price": 125,
        "currency": "credits",
        "category": "xp_point",
        "effect_key": "xp_boost",
        "xp": 250,
        "qty": 1,
    },
    "xp_chip_major": {
        "name": "📂 Combat Simulator Log",
        "desc": "Add 1000 XP to your commander. Essential for progression.",
        "price": 450,
        "currency": "credits",
        "category": "xp_point",
        "effect_key": "xp_boost",
        "xp": 1000,
        "qty": 1,
    },
    "xp_chip_relic": {
        "name": "🗂 Ancient Commander Core",
        "desc": "Add 5000 XP to your commander. Legendary for progression.",
        "price": 2000,
        "currency": "credits",
        "category": "xp_point",
        "effect_key": "xp_boost",
        "xp": 5000,
        "qty": 1,
    },

    # ── Premium (Bitcoin) ─────────────────────────────────────────────────
    "cold_wallet": {
        "name": "🔐 Cold Wallet",
        "desc": "Max Crypto Wastes protection. 45 minutes. Survives Market Crash.",
        "price": 50,
        "currency": "bitcoin",
        "category": "premium",
        "effect_key": "cold_wallet",
        "duration_m": 45,
        "qty": 1,
    },
    "xp_boost_2x": {
        "name": "💫 2× XP Boost (1h)",
        "desc": "Double XP for one hour.",
        "price": 80,
        "currency": "bitcoin",
        "category": "premium",
        "effect_key": "xp_boost",
        "qty": 1,
    },
    "resource_boost": {
        "name": "2️⃣ 2× Resources (1h)",
        "desc": "All node yields doubled for 1 hour.",
        "price": 60,
        "currency": "bitcoin",
        "category": "premium",
        "effect_key": "resource_boost",
        "qty": 1,
    },

    # ── Resources & Crates ────────────────────────────────────────────────
    "crate_wood_credits": {
        "name": "🪵 Wood Crate",
        "desc": "Random wood resources + small XP.",
        "price": 100,
        "currency": "credits",
        "category": "crates",
        "effect_key": "crate_unclaimed",
        "crate_type": "wood_crate",
        "qty": 1,
    },
    "crate_bronze_credits": {
        "name": "🥉 Bronze Crate",
        "desc": "Random bronze resources + XP.",
        "price": 250,
        "currency": "credits",
        "category": "crates",
        "effect_key": "crate_unclaimed",
        "crate_type": "bronze_crate",
        "qty": 1,
    },
    "crate_iron_credits": {
        "name": "⚙️ Iron Crate",
        "desc": "Random iron resources + solid XP.",
        "price": 500,
        "currency": "credits",
        "category": "crates",
        "effect_key": "crate_unclaimed",
        "crate_type": "iron_crate",
        "qty": 1,
    },
    "crate_super_credits": {
        "name": "🌟 Super Crate",
        "desc": "Best odds, biggest XP payout.",
        "price": 1000,
        "currency": "credits",
        "category": "crates",
        "effect_key": "crate_unclaimed",
        "crate_type": "super_crate",
        "qty": 1,
    },
    "crate_sector1_blueprint": {
        "name": "Sector 1 Blueprint Chest",
        "desc": "Contains Sector 1 schematics and blueprints.",
        "price": 1500,
        "currency": "credits",
        "category": "crates",
        "effect_key": "grant",
        "drop_table": ["blueprint_shield_v2", "blueprint_radar"],
        "qty": 1,
    },
    "food_1k": {
        "name": "🥫 Rations Pack (1,000)",
        "desc": "Feed your base.",
        "price": 50,
        "currency": "credits",
        "category": "resources",
        "effect_key": "resource_pack",
        "res_type": "food",
        "res_amount": 1000,
        "qty": 1,
    },
    "food_10k": {
        "name": "🥫 Rations Pack (10,000)",
        "desc": "Feed your base — bulk.",
        "price": 400,
        "currency": "credits",
        "category": "resources",
        "effect_key": "resource_pack",
        "res_type": "food",
        "res_amount": 10000,
        "qty": 1,
    },
    "wood_1k": {
        "name": "🪵 Wood Pack (1,000)",
        "desc": "Basic building resource.",
        "price": 50,
        "currency": "credits",
        "category": "resources",
        "effect_key": "resource_pack",
        "res_type": "wood",
        "res_amount": 1000,
        "qty": 1,
    },
    "wood_res": {
        "name": "🌲 Wood",
        "price": 10,
        "currency": "silver",
        "category": "resource",
    },
    "bronze_res": {
        "name": "🧱 Bronze",
        "price": 20,
        "currency": "silver",
        "category": "resource",
    },
    "iron_res": {
        "name": "⛓️ Iron",
        "price": 50,
        "currency": "silver",
        "category": "resource",
    },
    "stone_res": {
        "name": "💎 Stone",
        "price": 100,
        "currency": "silver",
        "category": "resource",
    },

    # ── Intel & Utility Items ─────────────────────────────────────────────
    "name_shield": {
        "name": "🔐 Name Shield",
        "price": 800,
        "currency": "silver",
        "category": "utility",
        "min_level": 5,
    },
    "scout_item": {
        "name": "📸 Scout",
        "price": 600,
        "currency": "silver",
        "category": "utility",
        "min_level": 6,
    },
    "anti_scout": {
        "name": "📴 Anti-Scout",
        "price": 500,
        "currency": "silver",
        "category": "utility",
        "min_level": 5,
    },
    "blackout_item": {
        "name": "⚫ Blackout",
        "price": 2000,
        "currency": "silver",
        "category": "utility",
        "min_level": 10,
    },

    # ── Traps, Combat Buffs & Defenses ────────────────────────────────────
    "buff_attack_100": {
        "name": "War God's Vow",
        "desc": "+100 Flat Attack bonus for 30 minutes.",
        "category": "attack",
        "price": 1200,
        "currency": "credits",
        "stat_buff": "attack",
        "flat_bonus": 100,
        "duration_sec": 1800,
    },
    "basic_shield": {
        "name": "🛡️ Basic Shield",
        "price": 500,
        "currency": "silver",
        "category": "shield",
        "effect": "10% damage reduction",
    },
    "iron_shield": {
        "name": "⚔️ Iron Shield",
        "price": 1500,
        "currency": "silver",
        "category": "shield",
        "effect": "25% damage reduction",
    },
    "legendary_shield": {
        "name": "💥 Legendary Shield",
        "price": 5000,
        "currency": "silver",
        "category": "shield",
        "effect": "50% damage reduction",
    },
    "spike_trap": {
        "name": "🗡️ Spike Trap",
        "price": 300,
        "currency": "silver",
        "category": "trap",
    },
    "fire_trap": {
        "name": "🔥 Fire Trap",
        "price": 600,
        "currency": "silver",
        "category": "trap",
    },
    "poison_trap": {
        "name": "☠️ Poison Trap",
        "price": 800,
        "currency": "silver",
        "category": "trap",
    },
    "tesla_coil": {
        "name": "⚡ Tesla Coil",
        "price": 1500,
        "currency": "silver",
        "category": "trap",
    },
    "2x_resources": {
        "name": "2️⃣ 2x Resources (1hr)",
        "price": 250,
        "currency": "silver",
        "category": "buff",
        "duration": 3600,
    },
    "3x_xp": {
        "name": "💫 3x XP (1hr)",
        "price": 400,
        "currency": "silver",
        "category": "buff",
        "duration": 3600,
    },
    "lucky_boost": {
        "name": "🍀 Lucky Boost (1hr)",
        "price": 350,
        "currency": "silver",
        "category": "buff",
        "duration": 3600,
    },
    "speed_boost": {
        "name": "⚡ Speed Boost (1hr)",
        "price": 300,
        "currency": "silver",
        "category": "buff",
        "duration": 3600,
    },
}


WEAPONS = {
    # ── Offensive Weapons ─────────────────────────────────────────────────
    "machine_gun_turret": {
        "name": "🔫 MACHINE GUN TURRET",
        "description": "Shoot opponent when they form word of target length. They lose 50% of round points + 100 silver.",
        "category": "offensive",
        "effect": "score_and_silver_damage",
        "damage_points": 0.5,
        "damage_silver": 100,
        "cost": {"silver": 1000},
        "price": 1000,
        "charges": 1,
        "cooldown_hours": 168,
        "rarity": "uncommon",
        "min_level": 5,
        "level": 10,
    },
    "plasma_cannon": {
        "name": "⚡ PLASMA CANNON",
        "description": "Heavy weapon. Opponent loses 75% of round points + 250 silver. 48-hour cooldown.",
        "category": "offensive",
        "effect": "score_and_silver_damage",
        "damage_points": 0.75,
        "damage_silver": 250,
        "cost": {"silver": 2500},
        "price": 2500,
        "charges": 1,
        "cooldown_hours": 48,
        "rarity": "rare",
        "min_level": 15,
        "level": 25,
    },
    "emp_blast": {
        "name": "💥 EMP BLAST",
        "description": "Disrupt opponent's next 3 words. They get 0 points from those words.",
        "category": "offensive",
        "effect": "disable_words",
        "disabled_word_count": 3,
        "cost": {"silver": 800},
        "price": 800,
        "charges": 2,
        "cooldown_hours": 72,
        "rarity": "uncommon",
        "min_level": 8,
        "level": 30,
    },

    # ── Stealers & Drains ─────────────────────────────────────────────────
    "xp_siphon": {
        "name": "🔋 XP SIPHON",
        "description": "Each valid word opponent gets this round: YOU gain their XP instead of them. They get 0 XP.",
        "category": "stealer",
        "effect": "steal_xp",
        "steal_percentage": 1.0,
        "cost": {"silver": 1200},
        "price": 1200,
        "charges": 1,
        "cooldown_hours": 24,
        "rarity": "rare",
        "min_level": 12,
    },
    "silver_siphon": {
        "name": "💰 SILVER SIPHON",
        "description": "Each valid word opponent gets: YOU gain silver equal to their word value. They get normal XP only.",
        "category": "stealer",
        "effect": "steal_silver",
        "steal_percentage": 1.0,
        "cost": {"silver": 1500},
        "charges": 1,
        "cooldown_hours": 24,
        "rarity": "rare",
        "min_level": 14,
    },
    "resource_drain": {
        "name": "🌀 RESOURCE DRAIN",
        "description": "Opponent loses 200 wood + 100 bronze per word they form.",
        "category": "stealer",
        "effect": "drain_resources",
        "drain_amounts": {"wood": 200, "bronze": 100},
        "cost": {"silver": 2000},
        "price": 2000,
        "charges": 1,
        "cooldown_hours": 48,
        "rarity": "rare",
        "min_level": 20,
    },
    "bitcoin_miner": {
        "name": "💰 BITCOIN MINER",
        "description": "Mines crypto during combat rounds.",
        "category": "weapon",
        "price": 1500,
        "cost": {"silver": 1500},
        "rarity": "rare",
        "min_level": 15,
    },

    # ── Extractors ────────────────────────────────────────────────────────
    "wood_extractor": {
        "name": "🌲 WOOD EXTRACTOR",
        "description": "Each word opponent forms: steal 300 wood from their base.",
        "category": "stealer",
        "effect": "steal_resource_type",
        "resource_type": "wood",
        "steal_amount": 300,
        "cost": {"silver": 800},
        "price": 800,
        "charges": 2,
        "cooldown_hours": 12,
        "rarity": "uncommon",
        "min_level": 7,
    },
    "bronze_extractor": {
        "name": "🧱 BRONZE EXTRACTOR",
        "description": "Each word opponent forms: steal 200 bronze from their base.",
        "category": "stealer",
        "effect": "steal_resource_type",
        "resource_type": "bronze",
        "steal_amount": 200,
        "cost": {"silver": 1000},
        "price": 1000,
        "charges": 2,
        "cooldown_hours": 12,
        "rarity": "uncommon",
        "min_level": 10,
    },
    "iron_extractor": {
        "name": "⛓️ IRON EXTRACTOR",
        "description": "Each word opponent forms: steal 150 iron from their base.",
        "category": "stealer",
        "effect": "steal_resource_type",
        "resource_type": "iron",
        "steal_amount": 150,
        "cost": {"silver": 1500},
        "price": 1500,
        "charges": 2,
        "cooldown_hours": 12,
        "rarity": "uncommon",
        "min_level": 12,
    },
    "diamond_extractor": {
        "name": "💎 DIAMOND EXTRACTOR",
        "description": "Each word opponent forms: steal 50 diamond from their base.",
        "category": "stealer",
        "effect": "steal_resource_type",
        "resource_type": "diamond",
        "steal_amount": 50,
        "cost": {"silver": 3000},
        "price": 3000,
        "charges": 1,
        "cooldown_hours": 24,
        "rarity": "rare",
        "min_level": 25,
    },
}