name: Deploy Game Server to VM

on:
  push:
    branches:
      - main  # If your default branch is 'master', change this to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/ubuntu/camera
            git pull
            sudo systemctl restart gameserver
